### ISSUE TITLE
Mailgun\Tests\Mock\Mailgun is not available on mailgun-php after version 2.1

### ISSUE THREAD

**Issue by alysson-azevedo** [narendravaghela/cakephp-mailgun#13]
I'm writing a pull request to make this plugin pass on Cake 3.6.

When i updated the composer.json, the mailgun-php was updated to the version 2.5.
On their [CHANGELOG](https://github.com/mailgun/mailgun-php/blob/master/CHANGELOG.md), lots of things was changed.

The main problem is that after 2.1, their "/tests/" directory is not shipped by composer, so now this line fails:
https://github.com/narendravaghela/cakephp-mailgun/blob/master/src/Mailer/Transport/MailgunTransport.php#L22

So, i'll force the composer to stick on the mailgun-php 2.1, and leave the update to 2.5 for another pull-request.

**Comment by narendravaghela** [comment]
@alysson-azevedo This is fixed in latest PR, right?

**Comment by alysson-azevedo** [comment]
Right. Thanks
