### ISSUE TITLE
Mailgun EU Support is missing.

### ISSUE THREAD

**Issue by biohazardious** [narendravaghela/cakephp-mailgun#15]
I am using this library with eu mailgun api. The problem is url is different than US. For now i edited the Mailgun.php $apiendpoint variable. It will be great to configure it from app.php.

**Comment by narendravaghela** [comment]
Hi @biohazardious 
Thanks for the suggestion. I will implement it in next release!

**Comment by narendravaghela** [comment]
Hi @biohazardious 
Please use `3.0.0`, you can customize the api endpoint from your `app.php`.
Also read https://github.com/narendravaghela/cakephp-mailgun/blob/master/UPGRADE.md

**Comment by biohazardious** [comment]
@narendravaghela,
Thanks for the good news. I will try it asap.
Cheers.
