### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by nikhil-twinspark** [narendravaghela/cakephp-mailgun#2]
Could not fetch https://api.github.com/repos/goetas/serializer/contents/composer.json?ref=813de268b702f501c873f90949495e497269b8ea, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+nikhil-ThinkPad-L460+2016-12-22+1329
to retrieve a token. It will be stored in "/home/nikhil/.composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by nikhil-twinspark** [comment]
The endpoint you've tried to access does not exist. Check your URL. 
This is the error

**Comment by narendravaghela** [comment]
@nikhil-twinspark 
Regarding your first comment, it is related to GitHub.
And the endpoint error, please make sure you have `ssl` mode true and refer to [Setup](https://github.com/narendravaghela/cakephp-mailgun#setup) for more information.

**Comment by narendravaghela** [comment]
Closing it due to no response.

**Comment by nikhil-twinspark** [comment]
ok
