### ISSUE TITLE
Class 'App\Controller\MailgunEmail' not found

### ISSUE THREAD

**Issue by agarzon** [narendravaghela/cakephp-mailgun#21]
Something is wrong with the namespace registry.

Following the doc step by step with cakephp 3.7

Instantiation fails.
$email = new MailgunEmail();

triggers: 
Class 'App\Controller\MailgunEmail' not found

**Comment by challgren** [comment]
You must be following the docs on the `master` branch, but using version 3.x. You can view the 3.x docs at https://github.com/narendravaghela/cakephp-mailgun/tree/v3.0.2 the MailgunEmail is coming out in version 4.0
