### ISSUE TITLE
Use MailgunEmail features in Mailers

### ISSUE THREAD

**Issue by peiblox** [narendravaghela/cakephp-mailgun#22]
When updating to version 4.0.0 and introducing the new `MailgunEmail` class, I don't know if you can use it in `Mailer` classes or you just have to use the default Email class.

It would be useful to use the `MailgunEmail` class methods inside `Mailer` configuration, like `enableDkim`, `setTags` and so.

**Comment by challgren** [comment]
So for my use case I have a custom `Mailer` and I check to make sure `$this->_email` is an instance of MailgunEmail and then I call the `setTags`, `enableDkim` etc.

Below is an snippet of my code

```php
public function statusChange(EntityInterface $entity, array $notify, array $old_status)
    {
        if ($this->_email instanceof MailgunEmail) {
            $this->_email->setRecipientVars($notify);
            $this->_email->setTags(['audit-status-change', 'tenant-' . $entity->get('tenant_id')]);
        }
        $this->setFrom('admin@domain.com')
            ->setEmailFormat(Email::MESSAGE_HTML)
            ->setViewVars(['old_status' => $old_status, 'energyAudit' => $entity])
            ->addTo(array_keys($notify))
            ->setSubject($entity->get('project_name') . ' has been updated')
            ->viewBuilder()->setTemplate('audit_status_change');

        return $this;
    }
```

**Comment by peiblox** [comment]
Hi,
thanks for your reply.

I was testing a little bit and I'm afraid that the class I'm getting in the `$this->_email` object is `Cake\Mailer\Email` instead of `MailgunEmail`.

I've configured a new type of transport and email profile, both called `mailgun` but I don't get the `MailgunEmail` class.

Everything else is working fine, so I don't know what I'm doing wrong. Thank you in advance.

**Comment by challgren** [comment]
You can initialize the Mailer with an Email class, first make sure you have `use MailerAwareTrait;` in your class. `$mailer = $this->getMailer('MyMailer', new MailgunEmail());`

**Comment by peiblox** [comment]
Thank you so much @challgren for the answer. Didn't realize that you can use the `MailerAwareTrait` to do that. 👍
