### ISSUE TITLE
making use of the status codes when there are errors returned from Mailgun

### ISSUE THREAD

**Issue by sdevore** [narendravaghela/cakephp-mailgun#24]
I wonder if the $response->getStatusCode(); and/ or the use of $response->isOk(); could be added to the returned object.  I realize that this might make the return from _sendEmail() a little different, but it would be nice to able to better manage errors.

**Comment by challgren** [comment]
OK I agree, however it would be a breaking change so a new major version would need to be released.

**Comment by challgren** [comment]
@sdevore would this be something you want to be in CakePHP 3.8 or CakePHP 4.x?

**Comment by sdevore** [comment]
Well given my client's cadence for being willing to spend for updating, I'd love it for 3 ;) but given it would likely be a breaking change, I think 4 would be a better target, plus that seems to be where you are working (given some of your slack answers)

**Comment by challgren** [comment]
Closing now that PR is open
