### ISSUE TITLE
Unknown email configuration "mailgun". 

### ISSUE THREAD

**Issue by jimeshgajera** [narendravaghela/cakephp-mailgun#5]
@narendravaghela 
I have configure cakephp mailgun as per your instructions. But it give me error as **"Unknown email configuration "mailgun". "**

**Comment by narendravaghela** [comment]
Can you share your app.php code? Also which CakePHP version do you use?

**Comment by jimeshgajera** [comment]
@narendravaghela 
below code of app.php

'EmailTransport' => [
        'default' => [
            'className' => 'Mail',
            // The following keys are used in SMTP transports
            'host' => 'localhost',
            'port' => 25,
            'timeout' => 30,
            'username' => 'user',
            'password' => 'secret',
            'client' => null,
            'tls' => null,
        ],

        'mailgun' => [
            'className' => 'MailgunEmail.Mailgun',
            'apiKey' => 'key-7520fe2772a15fccde2c5df814b32a4c', // your api key
            'domain' => 'mg.datanrich.com' // your sending domain
        ]
    ],

'Email' => [
        'default' => [
            'transport' => 'default',
            'from' => 'you@localhost',
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ]
    ]

**I have use "use Cake\Network\Email\Email;" in controller.**

**Comment by narendravaghela** [comment]
You need to set mailgun in both the config options Transport and Email. See this link for step by step guide - http://blog.narendravaghela.com/cakephp-send-transactional-emails-using-mailgun/

**Comment by jimeshgajera** [comment]
@narendravaghela 

I have follow step as per your guide. But still I am getting same error.

Is there anything remain to configure?

As I said, I have used **"use Cake\Network\Email\Email;"** in controller
