### ISSUE TITLE
Transport class "mailgun" not found.

### ISSUE THREAD

**Issue by d-grilo** [narendravaghela/cakephp-mailgun#7]
I've noticed that MailgunTransport.php uses "use Cake\Mailer\Email;"

If I'm not mistaken this namespace doesn't exist in versions prior to 3.1.

My app.php:
 
```
'EmailTransport' => [
...
 'mailgun' => [
            'className' => 'MailgunEmail.Mailgun',
            'apiKey' => 'key-xxxxxxxxxxxxxxxxxxxxxxxxxxx', 
            'domain' => 'sandboxxxxxxxxxxxxxxxxxxxxxxxxxxxx.mailgun.org' 
        ]
],
'Email' => [
'mailgun' => [
            'transport' => 'mailgun'
        ]

 ],
```

In my controller:

use Cake\Network\Email\Email;

` $email = new Email('mailgun');

        $result = $email->from(['foo@example.com' => 'Test'])

            ->to('xxxxx@hotmail.com')
            ->subject('newsletter')
            ->template('send', 'send')
            ->viewVars(['news' => $news, 'newsletter' => $newsletter, 'newsDestaque' => $newsDestaque, 'imagemDestaque' => $imagemDestaque, 'domain_id' => $domain_id])
            ->emailFormat('both')
            ->addHeaders(['o:tag' => 'testing'])
            ->addHeaders(['o:deliverytime' => strtotime('+1 Min')])
            ->send();`

**Comment by narendravaghela** [comment]
Right, the plugin needs to be updated to make it work with latest CakePHP 3.x versions.

**Comment by narendravaghela** [comment]
Please use older release for Cake 3.1 or less.
