### ISSUE TITLE
How to use inline attachments?

### ISSUE THREAD

**Issue by alysson-azevedo** [narendravaghela/cakephp-mailgun#8]
On cake, we use

```
$email->setAttachments([
    'logo.png' => [
        'file' => WWW_ROOT . Configure::read('App.imageBaseUrl') . 'logo.png',
        'contentId' => 'logo'
    ]
])
```

But on the [mailgun-php](https://github.com/mailgun/mailgun-php/blob/af98ed33071fb9336110e5b93448661355538aff/doc/attachments.md#inline-attachments) is

```
$mg->message()->send('example.com', [
  'from'    => 'bob@example.com', 
  'to'      => 'sally@example.com', 
  'subject' => 'Test inline attachments', 
  'text'    => 'Test',
  'inline' => [
    ['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']
  ]
]);
```

So, is it possible to send inline attachments with this plugin?

**Comment by alysson-azevedo** [comment]
Hi. I edited the MailgunTransport class and figured that if you add the line 
```
$this->_attachments['inline'] = $attachments;
``` 
after [this line](https://github.com/narendravaghela/cakephp-mailgun/blob/master/src/Mailer/Transport/MailgunTransport.php#L202), it works.

The problem is that the attachment will be send twice, so it's not a good solution

**Comment by narendravaghela** [comment]
Sending them twice is not a good idea. I will check what can be done for this.

**Comment by alysson-azevedo** [comment]
Hey, @narendravaghela did you check this issue?

Soon i'll need to send inline attachments, so i'll try to fix this issue somehow.
The way i'm thinking to handle this is on:

        if (!empty($attachments)) {
            $this->_attachments['attachment'] = $attachments;
        }

If $attachments' itens have the `contentId` property, i can shift them from the $attachments into a new variable and then `$this->_attachments['inline'] = $inlineAttachments;` or something like that.

What do you think?

**Comment by narendravaghela** [comment]
Hi @alysson-azevedo 
Didn't get time to check this plugin, sorry about that :)
I think the plugin needs to be updated in many ways as there is Cake 3.6 out now. I haven't used this plugin for a long time, so need to check for `inline` attachments. But the proposed solution looks good to me for now.
Also, please generate PRs for the fixes that you have made in this plugin, so others can take benefits.

**Comment by alysson-azevedo** [comment]
Ok, i'll look into that.
